import { StackingBehavior } from '../types/effects';
import { ResourceType } from '../types';

/**
 * Types of abilities in the game
 */
export enum AbilityType {
  STANDARD = 'standard',
  COMBAT = 'combat',
  PROC = 'proc',
  ITEM = 'item',
  FINISHER = 'finisher', // Combo point finisher abilities
}

/**
 * Maximum combo points a player can accumulate
 */
export const MAX_COMBO_POINTS = 5;

/**
 * Resource cost configuration for abilities that use non-mana resources
 */
export interface AbilityResourceCost {
  type: ResourceType;
  amount: number;
}

/**
 * How ability cooldowns are tracked
 */
export enum CooldownType {
  ROUNDS = 'rounds',
  SECONDS = 'seconds',
  USES = 'uses',
}

/**
 * Valid targets for abilities
 */
export enum TargetType {
  SELF = 'self',
  ENEMY = 'enemy',
  ALLY = 'ally',
  ROOM = 'room',
}

/**
 * Effect configuration within an ability
 */
export interface AbilityEffect {
  effectType: string; // Matches EffectType enum values from types/effects.ts
  payload: {
    damagePerTick?: number;
    healPerTick?: number;
    damageAmount?: number;
    healAmount?: number;
    statModifiers?: { [stat: string]: number };
    blockMovement?: boolean;
    blockCombat?: boolean;
    metadata?: { [key: string]: unknown };
  };
  durationTicks: number;
  tickInterval: number;
  stackingBehavior?: StackingBehavior;
  name?: string;
  description?: string;
}

/**
 * Requirements to use an ability
 */
export interface AbilityRequirements {
  level?: number;
  stats?: { [stat: string]: number };
}

/**
 * Combo point scaling configuration for finisher abilities
 */
export interface ComboScaling {
  /** Base damage of the finisher */
  baseDamage: number;
  /** Additional damage per combo point */
  damagePerPoint: number;
  /** Maximum combo points to scale with (typically MAX_COMBO_POINTS) */
  maxPoints: number;
}

/**
 * Template defining an ability
 */
export interface AbilityTemplate {
  id: string;
  name: string;
  description: string;
  type: AbilityType;
  mpCost: number;
  cooldownType: CooldownType;
  cooldownValue: number;
  targetType: TargetType;
  effects: AbilityEffect[];
  requirements?: AbilityRequirements;
  procChance?: number;
  consumesItem?: boolean;

  // === Class Binding System ===
  /** Class IDs that can use this ability. If empty/undefined, all classes can use it. */
  classRestrictions?: string[];

  // === Multi-Resource Cost System ===
  /** Resource cost (alternative to mpCost for non-mana classes) */
  resourceCost?: AbilityResourceCost;

  // === Combo Point System (Thief/Rogue classes) ===
  /** Number of combo points generated by this ability (0-2) */
  comboPointsGenerated?: number;
  /** If true, this is a finisher that consumes ALL combo points */
  comboPointsConsumed?: boolean;
  /** Damage scaling based on combo points (for finishers) */
  comboScaling?: ComboScaling;
}

/**
 * Cooldown state for a single ability
 */
export interface AbilityCooldownState {
  lastUsedRound?: number;
  lastUsedTimestamp?: number;
  usesRemaining?: number;
}

/**
 * All cooldowns for a player
 */
export interface PlayerCooldowns {
  [abilityId: string]: AbilityCooldownState;
}
